/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '@/components/SideBarComponent'
const inter = Inter({ subsets: ['latin'] })
import '../globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ActivityLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: 'flex' }}>
        <SideBar />
        {children}
      </body>
    </html>
  )
}
